guru:
  jms:
    user: ymlJmsUser
    password: ymlJmsPass
    url: ymlJmsUrl

# file separator inside YML file
---

spring:
  profiles: fr
guru:
  jms:
    user: fr_ymlJmsUser
    password: fr_ymlJmsPass
    url: fr_ymlJmsPass